import assert from "node:assert/strict";
import { mkdtemp,rm } from "node:fs/promises";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { startServer } from "../src/server/index.js";

process.env.MODEL_VERITY_ALLOW_PRIVATE_ENDPOINTS="1";process.env.MODEL_VERITY_DISABLE_KEYCHAIN="1";process.env.MODEL_VERITY_MASTER_KEY="candidate-smoke-only";process.env.MODEL_VERITY_V2_EXPLORATORY_DEFAULT="1";
const dataDir=await mkdtemp(join(tmpdir(),"mv-v2-candidate-"));
const mock=createServer(async(req,res)=>{let raw="";for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);const prompt=body.messages?.[1]?.content??body.input??"";const content=/coin/i.test(prompt)?"heads":/color/i.test(prompt)?"blue":/number/i.test(prompt)?"7":/letter/i.test(prompt)?"a":"cat";res.setHeader("content-type","application/json");res.end(JSON.stringify({model:"candidate-mock",choices:[{message:{content}}],usage:{prompt_tokens:10,completion_tokens:1}}));});
await new Promise<void>((resolve)=>mock.listen(0,"127.0.0.1",resolve));const address=mock.address();const mockPort=typeof address==="object"&&address?address.port:0;
const app=await startServer({port:0,dataDir,webRoot:join(process.cwd(),"dist/web")});
try{const call=async(path:string,init?:RequestInit)=>{const response=await fetch(`${app.state.url}${path}`,{...init,headers:{"content-type":"application/json",...init?.headers}});const value=await response.json();assert.ok(response.ok,`${response.status} ${JSON.stringify(value)}`);return value;};const health=await call("/api/health");assert.equal(health.ok,true);const html=await(await fetch(app.state.url)).text();assert.match(html,/<div id="root">/);const policy=await call("/api/v2/policy");assert.equal(policy.strongConclusionsEnabled,false);const provider=await call("/api/providers",{method:"POST",body:JSON.stringify({name:"Candidate mock",protocol:"openai-compatible",baseUrl:`http://127.0.0.1:${mockPort}/v1`,apiKey:"secret",models:["openai/gpt-4o-mini"],role:"audit"})});const expiresAt=new Date(Date.now()+60000).toISOString();const auth=await call("/api/v2/budget-authorizations",{method:"POST",body:JSON.stringify({providerIds:[provider.id],models:["openai/gpt-4o-mini"],maxEndpointRequests:20,maxInputTokens:10000,maxOutputTokens:1000,maxAttemptsPerEndpoint:1,expiresAt})});const run=await call("/api/v2/verification-runs",{method:"POST",body:JSON.stringify({mode:"screening",providerId:provider.id,model:"openai/gpt-4o-mini",referenceId:"builtin:pamela:openai/gpt-5.4-mini",profile:"quick",protocolComparability:"P3",referenceLevel:"L3",identity:{declared:{vendor:"OpenAI",product:"GPT-4o mini",surface:"unknown"},observed:{targetProtocol:"openai-compatible"}},budget:{authorizationId:auth.id,maxPairs:20,maxEndpointRequests:20,maxAttemptsPerEndpoint:1,expiresAt}})});let complete=run;for(let i=0;i<200&&["queued","running"].includes(complete.status);i++){await new Promise((resolve)=>setTimeout(resolve,20));complete=await call(`/api/v2/verification-runs/${run.id}`);}assert.equal(complete.status,"completed",complete.error);assert.equal(complete.result.conclusion.strongConclusion,false);for(const format of ["json","markdown","csv"]){const response=await fetch(`${app.state.url}/api/v2/verification-runs/${run.id}/export?format=${format}`);assert.equal(response.status,200);assert.ok((await response.text()).length>100);}const legacy=await fetch(`${app.state.url}/api/audits`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});assert.equal(legacy.status,410);console.log(JSON.stringify({ok:true,url:app.state.url,runId:run.id,strongConclusionsEnabled:policy.strongConclusionsEnabled,exports:["json","markdown","csv"],legacyWriteStatus:legacy.status},null,2));}finally{await app.close();await new Promise<void>((resolve)=>mock.close(()=>resolve()));await rm(dataDir,{recursive:true,force:true});}
